### ISSUE TITLE
Updating to 4.13 broke; d3.merge(...).transition is not a function

### ISSUE THREAD

**Issue by Aftabnack** [d3/d3#3267]
Hi, I'm unsure whether this problem is with `d3.selection` or `d3.transition`, but the following code broke with an error message `d3.merge(...).transition` is not a function.

This is working on `4.12.2` but broke when I bumped it to `4.13.0`

```javascript
  //Existing nodes
  const createdNodes = treeGroup
    .selectAll('g.node')
    .classed('highlight', false)
    .classed('selected', d => d.data.id === currentSelected)
    .data(nodes, d => d.id || ((d.id = ++uniqueID), d.id));
.
.
.
  //Entry
  const newNodes = createdNodes
    .enter()
    .append('g')
    .attr('class', 'node')
    .classed('highlight', d => d.shouldHighlight)
    .classed('selected', d => d.data.id === currentSelected)
    .attr('transform', `translate(${source.x0}, ${source.y0})`);
.
.
.
  //Update
  const nodeUpdate = createdNodes
    .merge(newNodes)
    .transition()
    .duration(duration)
    .attr('transform', d => `translate(${d.x}, ${d.y})`);

```

PS: I checked the release notes to make sure that there were no breaking changes mentioned.

**Comment by mbostock** [comment]
Duplicate of d3/d3#3256. Possible fixes: 1. Upgrade to 5.0. 2. Use the D3 modules directly rather than the `d3` default bundle. 3. Use your package manager, e.g., yarn’s resolutions feature, to pin the versions of the D3 modules so they are consistent with the `d3` package you are using.
